#!/usr/bin/env node
// Generates src/data/curriculumServer.js from src/data/curriculum.ts
// Uses esbuild (bundled with Vite) to compile TypeScript on-the-fly.
// Run: node scripts/generateServerData.js

const path = require('path');
const fs = require('fs');
const os = require('os');

const root = path.resolve(__dirname, '..');
const srcFile = path.join(root, 'src', 'data', 'curriculum.ts');
const outFile = path.join(root, 'src', 'data', 'curriculumServer.js');
const tmpFile = path.join(os.tmpdir(), `curriculum_tmp_${Date.now()}.cjs`);

try {
  const { buildSync } = require('esbuild');

  buildSync({
    entryPoints: [srcFile],
    bundle: false,
    format: 'cjs',
    platform: 'node',
    outfile: tmpFile,
    target: 'node18',
    // 'import type' statements are stripped automatically by esbuild
  });

  // Require the compiled module — WORLDS is the default export
  const mod = require(tmpFile);
  const worlds = mod.WORLDS || mod.default?.WORLDS || Object.values(mod)[0];

  if (!Array.isArray(worlds) || worlds.length === 0) {
    throw new Error('Could not extract WORLDS array from compiled module');
  }

  const header = [
    '// AUTO-GENERATED by scripts/generateServerData.js — DO NOT EDIT MANUALLY',
    `// Generated: ${new Date().toISOString()} — ${worlds.length} worlds`,
    '',
    'module.exports = ' + JSON.stringify(worlds, null, 2) + ';',
    '',
  ].join('\n');

  fs.writeFileSync(outFile, header, 'utf8');
  console.log(`✅ curriculumServer.js — ${worlds.length} worlds, ${worlds.reduce((n, w) => n + w.questions.length, 0)} questions`);

  try { fs.unlinkSync(tmpFile); } catch {}
} catch (err) {
  console.error('❌ generateServerData failed:', err.message);
  process.exit(1);
}
